var spawn = require('child_process').spawn
  , COMMAND = 'source-highlight';

/**
 *  For each code block with an info string call source-highlight(1) and 
 *  rewrite the output nodes to include the highlighted response.
 *
 *  @function highlight
 *
 *  @param through module for subclassing streams.
 *  @param ast module for working with ast nodes.
 *  @param opts options passed to the `transform` function.
 *
 *  @option {String} src source language, overrides info string.
 *  @option {String} out output format.
 *  @option {Boolean} lines number lines in highlighted output.
 *  @option {Boolean} preserve Keep a `<code>` element in the result.
 */
function highlight(through, ast, opts) {
  var Node = ast.Node;

  function transform(chunk, encoding, cb) {
    var scope = this;

    if(Node.is(chunk, Node.CODE_BLOCK) && (opts.src || chunk.info)) {
      var lang = chunk.info.split(/\s+/)[0]
        , literal = chunk.literal
        , out = opts.out || 'html'
        , args = [
            '--src-lang',
            opts.src || lang,
            '--out-format',
            out
          ]
        , result = new Buffer(0);

      // number source code lines
      if(opts.lines) {
        literal = literal.replace(/\n$/, '');
        args.push('--line-number= '); 
      }

      var ps = spawn(COMMAND, args);

      ps.stdout.on('data', function(data) {
        result = Buffer.concat(
          [result, data], result.length + data.length);
      })

      ps.once('close', function(code) {
        if(code === 0 && result.length) {

          if(out === 'html' || out === 'html-css') {
            var doc = ast.parse('' + result);

            // remove the generated by comment
            doc.firstChild.unlink();

            // add chunks to the stream
            var next = doc.firstChild;
            if(opts.preserve) {
              var element = '<pre><code class="language-' + lang + '">'
              next.literal = next.literal.replace(/^<pre>/, element);
              next.literal = next.literal.replace(/<\/pre>/, '</code></pre>');
            }
            while(next) {
              //console.error(next.literal)
              scope.push(next); 
              next = next.next;
            }
          //}else if(out === 'esc') {

          }else{
            chunk.literal = '' + result;
            scope.push(chunk);
          }

          cb();
        }else{
          cb(null, chunk); 
        }
      })

      ps.stdin.end(literal);
    }else{
      cb(null, chunk);
    }
  }

  return through.transform(transform);
}

module.exports = highlight;
